# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='post',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
    ]
