# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160618_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
