# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='joined_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
