# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_joined_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_players',
        ),
    ]
